name: Build, Test, and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to main

jobs:
  build-test-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for advanced Docker build)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry (GHCR)
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      # Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ghcr.io/tambinos/easy-notes:latest .

      # Run the Docker container to test if it works
      - name: Run Docker container and test
        run: |
          docker run -d --name easy-notes-container ghcr.io/tambinos/easy-notes:latest
          
          # Wait for the container to initialize (adjust timing if needed)
          sleep 120
          
          # Run a basic health check (modify if your container needs a specific check)
          docker exec easy-notes-container curl -f http://localhost || exit 1
          
          # Clean up: Stop and remove the container
          docker stop easy-notes-container
          docker rm easy-notes-container

      # Push the image to GHCR
      - name: Push the Docker image to GHCR
        run: |
          docker push ghcr.io/tambinos/easy-notes:latest
